import { getByWeek } from '$lib/functions';
export async function load({ params }) {
	const slug = Number(params.slug);
	const response = await getByWeek(slug);

	return { food: response };
}

// https://kit.svelte.dev/docs/adapter-vercel#incremental-static-regeneration
// set expiration time (in seconds) before the cached asset will be re-generated by invoking the Serverless Function.
// Setting the value to `false` means it will never expire.
export const config = {
	isr: { expiration: false }
};
